[tool.poetry]
name = "pyrorb"
version = "0.1.0"
description = ""
authors = ["Ashkan Shokri <ashkan.shokri@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]

[tool.poetry.group.dev.dependencies]





[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
